image: Visual Studio 2017

before_build:
    nuget restore Rest.ClientRuntime.Test/Rest.ClientRuntime.Test.sln

configuration:
  - Release

assembly_info:
  patch: true
  file: MyVersion.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

artifacts:
  - path: 'Rest.ClientRuntime.Test/Rest.ClientRuntime.Test/bin/Release/Rest.ClientRuntime.Test.*.nupkg'
