image: Visual Studio 2017
before_build:
    nuget restore Rest.ClientRuntime.Test/Rest.ClientRuntime.Test.sln
configuration:
  - Release
artifacts:
  - path: 'Rest.ClientRuntime.Test/Rest.ClientRuntime.Test/bin/Release/Rest.ClientRuntime.Test.*.nupkg'