image: Visual Studio 2017

before_build:
    nuget restore Rest.ClientRuntime.Test/Rest.ClientRuntime.Test.sln

configuration:
  - Release

artifacts:
  - path: 'Rest.ClientRuntime.Test/Rest.ClientRuntime.Test/bin/Release/Rest.ClientRuntime.Test.*.nupkg'

after_build:
  - ps: Get-ChildItem ./Rest.ClientRuntime.Test/Rest.ClientRuntime.Test/bin/Release/Rest.ClientRuntime.Test.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }