version: 1.0.200.{build}
image: Visual Studio 2017
configuration: Debug
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore Microsoft.Rest.ClientRuntime.Test.sln
build:
  verbosity: minimal
artifacts:
- path: Microsoft.Rest.ClientRuntime.Test/bin/Debug/Microsoft.Rest.ClientRuntime.Test.*.nupkg
