version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore Microsoft.Rest.ClientRuntime.Test.sln
build:
  verbosity: minimal
artifacts:
- path: Microsoft.Rest.ClientRuntime.Test/bin/Release/Microsoft.Rest.ClientRuntime.Test.*.nupkg